### ISSUE TITLE
Missing check of "inout" in ContainerElementType template

### ISSUE THREAD

**Issue by yshui** [economicmodeling/containers#65]
"inout" type are considered as immutable in that template.

**Comment by Hackerpilot** [comment]
Variables cannot be `inout`, so trying to support this would not make sense.

**Comment by yshui** [comment]
I'm not sure what you meant. 

I found this problem when I trying to:
```D
struct A {
    HashSet!(ulong*) a;
    inout(ulong*) func() inout {
        return a.range.front;
    }
}
```

**Comment by Hackerpilot** [comment]
The `ContainerStorageType` template is used when declaring variables inside of many of the containers. Example from the hash set: `ContainerStorageType!T value;` Because variables cannot be `inout` I don't think that supporting `inout` in that template will work. (I probably tried it at some point in the past, but I don't remember it exactly.)
